# -*- coding: utf-8 -*-
"""Derara ShCNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q9gtxZSjpKr--U9cR2tGlw9Ws3ALJ1j2
"""

!pip install opendatasets

import opendatasets as od

od.download("https://www.kaggle.com/datasets/iarunava/cell-images-for-detecting-malaria")

import os

dataset_path = "/content/cell-images-for-detecting-malaria/cell_images"

print(os.listdir(dataset_path))

dataset_path = "/content/cell-images-for-detecting-malaria/cell_images/cell_images"

import os

print(os.listdir(dataset_path))

from torchvision import transforms

import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import os
import random

classes = ['Parasitized', 'Uninfected']

plt.figure(figsize=(8, 4))

for i, cls in enumerate(classes):

    img_folder = os.path.join(dataset_path, cls)
    img_name = random.choice(os.listdir(img_folder))
    img_path = os.path.join(img_folder, img_name)

    img = mpimg.imread(img_path)

    plt.subplot(1, 2, i + 1)
    plt.imshow(img)
    plt.title(cls)
    plt.axis("off")

plt.show()

import os
import matplotlib.pyplot as plt

classes = ['Parasitized', 'Uninfected']

counts = []

for cls in classes:
    folder_path = os.path.join(dataset_path, cls)
    counts.append(len(os.listdir(folder_path)))

# Colors for each class
colors = ['red', 'green']

plt.figure(figsize=(6,4))

bars = plt.bar(classes, counts, color=colors)

# Add values on top
for bar in bars:
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2,
             height + 50,
             str(height),
             ha='center')

plt.title("Class Distribution (Malaria Dataset)")
plt.ylabel("Number of Images")
plt.xlabel("Class")

plt.show()

import os
import matplotlib.pyplot as plt

classes = ['Parasitized', 'Uninfected']

counts = []

for cls in classes:
    folder_path = os.path.join(dataset_path, cls)
    counts.append(len(os.listdir(folder_path)))

# Colors
colors = ['red', 'green']

plt.figure(figsize=(6,6))

plt.pie(
    counts,
    labels=classes,
    colors=colors,
    autopct='%1.1f%%',
    startangle=90,
    explode=(0.05, 0.05),  # slight separation
    shadow=True
)

plt.title("Class Distribution (Malaria Dataset)")
plt.show()

from torchvision import datasets

dataset = datasets.ImageFolder(
    root=dataset_path,
    transform=None
)

train_transform = transforms.Compose([
    transforms.Resize((128, 128)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.RandomRotation(10),
    transforms.ToTensor(),
    transforms.Normalize([0.5,0.5,0.5],[0.5,0.5,0.5])
])

test_transform = transforms.Compose([
    transforms.Resize((128, 128)),
    transforms.ToTensor(),
    transforms.Normalize([0.5,0.5,0.5],[0.5,0.5,0.5])
])

from torchvision import datasets

dataset = datasets.ImageFolder(
    root=dataset_path,
    transform=None
)

from torch.utils.data import random_split

train_size = int(0.8 * len(dataset))
val_size = int(0.1 * len(dataset))
test_size = len(dataset) - train_size - val_size

train_set, val_set, test_set = random_split(
    dataset,
    [train_size, val_size, test_size]
)

train_set.dataset.transform = train_transform
val_set.dataset.transform = test_transform
test_set.dataset.transform = test_transform

train_dataset = train_set
val_dataset = val_set
test_dataset = test_set

from torch.utils.data import DataLoader

train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=32, shuffle=False)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

print("Classes:", dataset.classes)
print("Train:", len(train_dataset))
print("Val:", len(val_dataset))
print("Test:", len(test_dataset))

import torch
import torch.nn as nn

class MalariaCNN(nn.Module):

    def __init__(self):
        super(MalariaCNN, self).__init__()

        self.features = nn.Sequential(

            # Block 1
            nn.Conv2d(3, 32, 3, padding=1),
            nn.BatchNorm2d(32),
            nn.ReLU(),
            nn.MaxPool2d(2),

            # Block 2
            nn.Conv2d(32, 64, 3, padding=1),
            nn.BatchNorm2d(64),
            nn.ReLU(),
            nn.MaxPool2d(2),

            # Block 3
            nn.Conv2d(64, 128, 3, padding=1),
            nn.BatchNorm2d(128),
            nn.ReLU(),
            nn.MaxPool2d(2),

            # Block 4
            nn.Conv2d(128, 256, 3, padding=1),
            nn.BatchNorm2d(256),
            nn.ReLU(),
            nn.MaxPool2d(2),
        )

        self.classifier = nn.Sequential(
            nn.AdaptiveAvgPool2d(1),
            nn.Flatten(),
            nn.Linear(256, 1)   # binary logit
        )

    def forward(self, x):
        x = self.features(x)
        x = self.classifier(x)
        return x

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = MalariaCNN().to(device)

import torch.optim as optim

criterion = nn.BCEWithLogitsLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

def train_model(model, train_loader, val_loader, epochs=10):

    for epoch in range(epochs):

        # -------- TRAIN --------
        model.train()
        train_loss = 0

        for images, labels in train_loader:

            images = images.to(device)
            labels = labels.float().unsqueeze(1).to(device)

            optimizer.zero_grad()

            outputs = model(images)
            loss = criterion(outputs, labels)

            loss.backward()
            optimizer.step()

            train_loss += loss.item()

        # -------- VALIDATION --------
        model.eval()
        correct = 0
        total = 0
        val_loss = 0

        with torch.no_grad():
            for images, labels in val_loader:

                images = images.to(device)
                labels = labels.float().unsqueeze(1).to(device)

                outputs = model(images)
                loss = criterion(outputs, labels)

                val_loss += loss.item()

                preds = torch.sigmoid(outputs)
                predicted = (preds > 0.5).float()

                correct += (predicted == labels).sum().item()
                total += labels.size(0)

        acc = correct / total

        print(f"Epoch [{epoch+1}/{epochs}] "
              f"Train Loss: {train_loss:.4f} "
              f"Val Loss: {val_loss:.4f} "
              f"Val Acc: {acc:.4f}")

train_model(model, train_loader, val_loader, epochs=10)

from sklearn.metrics import confusion_matrix, accuracy_score
import numpy as np

model.eval()

y_true = []
y_pred = []

with torch.no_grad():
    for images, labels in test_loader:

        images = images.to(device)
        labels = labels.to(device)

        outputs = model(images)
        preds = torch.sigmoid(outputs)
        preds = (preds > 0.5).int()

        y_true.extend(labels.cpu().numpy())
        y_pred.extend(preds.cpu().numpy())

acc = accuracy_score(y_true, y_pred)

print("Test Accuracy:", acc)

from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score
import numpy as np

model.eval()

y_true = []
y_pred = []

with torch.no_grad():
    for images, labels in test_loader:

        images = images.to(device)
        labels = labels.to(device)

        outputs = model(images)
        preds = torch.sigmoid(outputs)
        preds = (preds > 0.5).int()

        y_true.extend(labels.cpu().numpy())
        y_pred.extend(preds.cpu().numpy())

# Convert to numpy arrays (safe)
y_true = np.array(y_true)
y_pred = np.array(y_pred)

# Metrics
acc = accuracy_score(y_true, y_pred)
precision = precision_score(y_true, y_pred)
recall = recall_score(y_true, y_pred)

print("Test Accuracy:", acc)
print("Precision:", precision)
print("Recall:", recall)

import matplotlib.pyplot as plt

# Metric names
metrics = ['Accuracy', 'Precision', 'Recall']

# Metric values
values = [acc, precision, recall]

# Colors
colors = ['blue', 'green', 'orange']

# Plot
plt.figure(figsize=(8,5))

bars = plt.bar(metrics, values, color=colors)

# Add values on bars
for bar in bars:
    height = bar.get_height()

    plt.text(
        bar.get_x() + bar.get_width()/2,
        height + 0.01,
        f"{height:.4f}",
        ha='center',
        fontsize=11
    )

# Labels
plt.ylim(0, 1.1)

plt.title("Model Evaluation Metrics")
plt.ylabel("Score")

plt.grid(axis='y')

plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

cm = confusion_matrix(y_true, y_pred)

sns.heatmap(cm, annot=True, fmt="d",
            xticklabels=['Parasitized','Uninfected'],
            yticklabels=['Parasitized','Uninfected'])

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

!pip install grad-cam

from pytorch_grad_cam import GradCAM
from pytorch_grad_cam.utils.image import show_cam_on_image

target_layer = model.features[-2]

cam = GradCAM(
    model=model,
    target_layers=[target_layer]
)

image, label = test_dataset[0]

input_tensor = image.unsqueeze(0).to(device)

grayscale_cam = cam(input_tensor=input_tensor)[0]

import numpy as np
import matplotlib.pyplot as plt

model.eval()

plt.figure(figsize=(16, 10))  # bigger grid

for i in range(12):  # 3 x 4 = 12 images

    # 1. Get image
    image, label = test_dataset[i]

    # 2. Prepare input
    input_tensor = image.unsqueeze(0).to(device)

    # 3. Grad-CAM
    grayscale_cam = cam(input_tensor=input_tensor)[0]

    # 4. Convert image
    img = image.permute(1, 2, 0).cpu().numpy()
    img = (img - img.min()) / (img.max() - img.min())

    # 5. Overlay CAM
    visualization = show_cam_on_image(img, grayscale_cam, use_rgb=True)

    # 6. Plot in grid (3 rows, 4 cols)
    plt.subplot(3, 4, i + 1)
    plt.imshow(visualization)
    plt.title(f"{label}", fontsize=10)
    plt.axis("off")

plt.tight_layout()
plt.show()

def get_gradcam_heatmap(image, cam, device):

    input_tensor = image.unsqueeze(0).to(device)

    # Grad-CAM output
    grayscale_cam = cam(input_tensor=input_tensor)[0]

    return grayscale_cam

import numpy as np
from pytorch_grad_cam.utils.image import show_cam_on_image

def overlay_heatmap(image, heatmap):

    # convert tensor → numpy (H, W, C)
    img = image.permute(1, 2, 0).cpu().numpy()

    # normalize image
    img = (img - img.min()) / (img.max() - img.min())
    img = np.clip(img, 0, 1)

    # overlay heatmap
    visualization = show_cam_on_image(img, heatmap, use_rgb=True)

    return visualization

import matplotlib.pyplot as plt

model.eval()

image, label = test_dataset[0]

heatmap = get_gradcam_heatmap(image, cam, device)
result = overlay_heatmap(image, heatmap)

plt.figure(figsize=(5,5))
plt.imshow(result)
plt.title(f"Grad-CAM | Label: {label}")
plt.axis("off")
plt.show()

plt.figure(figsize=(20, 8))

for i in range(10):

    image, label = test_dataset[i]

    heatmap = get_gradcam_heatmap(image, cam, device)
    result = overlay_heatmap(image, heatmap)

    plt.subplot(2, 5, i + 1)
    plt.imshow(result)
    plt.title(label)
    plt.axis("off")

plt.tight_layout()
plt.show()

import torch
import numpy as np
import matplotlib.pyplot as plt

model.eval()

def get_saliency(image, model):

    image = image.unsqueeze(0).to(device)
    image.requires_grad = True

    output = model(image)
    score = torch.sigmoid(output)

    model.zero_grad()
    score.backward()

    saliency = image.grad.abs().squeeze().cpu().numpy()
    saliency = np.max(saliency, axis=0)

    return saliency

def plot_saliency(saliency, label, i):

    plt.subplot(2, 5, i + 1)
    plt.imshow(saliency, cmap="inferno")
    plt.title(f"{label}", fontsize=10)
    plt.axis("off")

plt.figure(figsize=(20, 8))

for i in range(10):

    # load image
    image, label = test_dataset[i]

    # compute saliency
    saliency = get_saliency(image, model)

    # plot
    plot_saliency(saliency, label, i)

plt.tight_layout()
plt.show()

!pip install lime

import torch
import numpy as np
import matplotlib.pyplot as plt

from lime import lime_image
from skimage.segmentation import mark_boundaries

def predict(images):

    model.eval()
    batch = torch.tensor(images).permute(0,3,1,2).float().to(device)

    with torch.no_grad():
        outputs = model(batch)
        probs = torch.sigmoid(outputs).cpu().numpy()

        # binary classification → [p, 1-p]
        probs = np.hstack([1 - probs, probs])

    return probs

explainer = lime_image.LimeImageExplainer()

image, label = test_dataset[0]

img = image.permute(1,2,0).cpu().numpy()
img = (img - img.min()) / (img.max() - img.min())

import matplotlib.pyplot as plt
from skimage.segmentation import mark_boundaries

model.eval()

plt.figure(figsize=(20, 10))  # large grid

for i in range(10):

    # 1. Get image
    image, label = test_dataset[i]

    img = image.permute(1,2,0).cpu().numpy()
    img = (img - img.min()) / (img.max() - img.min())

    # 2. Explain instance
    explanation = explainer.explain_instance(
        img,
        predict,
        top_labels=1,
        hide_color=0,
        num_samples=1000
    )

    # 3. Get mask
    temp, mask = explanation.get_image_and_mask(
        explanation.top_labels[0],
        positive_only=True,
        num_features=5,
        hide_rest=False
    )

    # 4. Plot in grid (2 rows × 5 cols)
    plt.subplot(2, 5, i + 1)
    plt.imshow(mark_boundaries(temp, mask))
    plt.title(f"{label}", fontsize=10)
    plt.axis("off")

plt.tight_layout()
plt.show()

!pip install gradio

!pip install gradio torch torchvision

torch.save(model.state_dict(), "malaria_cnn.pth")

# ==========================================
# INSTALL
# ==========================================

!pip install gradio torch torchvision

# ==========================================
# IMPORTS
# ==========================================

import gradio as gr
import torch
import torch.nn as nn
import torchvision.transforms as transforms

from PIL import Image

# ==========================================
# MODEL
# ==========================================

class MalariaCNN(nn.Module):

    def __init__(self):
        super(MalariaCNN, self).__init__()

        self.features = nn.Sequential(

            nn.Conv2d(3, 32, 3, padding=1),
            nn.BatchNorm2d(32),
            nn.ReLU(),
            nn.MaxPool2d(2),

            nn.Conv2d(32, 64, 3, padding=1),
            nn.BatchNorm2d(64),
            nn.ReLU(),
            nn.MaxPool2d(2),

            nn.Conv2d(64, 128, 3, padding=1),
            nn.BatchNorm2d(128),
            nn.ReLU(),
            nn.MaxPool2d(2),

            nn.Conv2d(128, 256, 3, padding=1),
            nn.BatchNorm2d(256),
            nn.ReLU(),
            nn.MaxPool2d(2),
        )

        self.classifier = nn.Sequential(
            nn.AdaptiveAvgPool2d(1),
            nn.Flatten(),
            nn.Linear(256, 1)
        )

    def forward(self, x):

        x = self.features(x)
        x = self.classifier(x)

        return x

# ==========================================
# DEVICE
# ==========================================

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

# ==========================================
# LOAD MODEL
# ==========================================

model = MalariaCNN().to(device)

model.load_state_dict(
    torch.load(
        "malaria_cnn.pth",
        map_location=device
    )
)

model.eval()

# ==========================================
# IMAGE TRANSFORM
# ==========================================

transform = transforms.Compose([

    transforms.Resize((128,128)),

    transforms.ToTensor(),

    transforms.Normalize(
        [0.5,0.5,0.5],
        [0.5,0.5,0.5]
    )
])

# ==========================================
# PREDICTION FUNCTION
# ==========================================

def predict(image):

    image = image.convert("RGB")

    tensor = transform(image)\
        .unsqueeze(0)\
        .to(device)

    with torch.no_grad():

        output = model(tensor)

        prob = torch.sigmoid(output).item()

    # CORRECT LABEL MAPPING
    if prob > 0.5:

        label = "Uninfected"
        icon = "🟢"
        status = "Healthy Cell"

    else:

        label = "Parasitized"
        icon = "🔴"
        status = "Infected Cell"

    return {
        "Prediction": f"{icon} {label}",
        "Status": status,
        "Confidence": round(prob, 4)
    }

# ==========================================
# PROFESSIONAL THEME
# ==========================================

theme = gr.themes.Soft(

    primary_hue="blue",
    secondary_hue="green",
    neutral_hue="slate",

    font=["Poppins", "sans-serif"]
)

# ==========================================
# DASHBOARD UI
# ==========================================

demo = gr.Interface(

    fn=predict,

    inputs=gr.Image(
        type="pil",
        label="Upload Malaria Cell Image"
    ),

    outputs=gr.JSON(
        label="Prediction Result"
    ),

    title="""
    <div style='text-align:center'>

    <h1 style='font-size:40px;
               color:#b30000;'>

    🦠 Malaria Cell Classification AI

    </h1>

    <p style='font-size:18px;
              color:#2c3e50;'>

    CNN-Based Medical Diagnosis System

    </p>

    </div>
    """,

    description="""
    Upload a microscopic blood smear image
    to detect malaria infection.
    """,

    theme=theme
)

# ==========================================
# LAUNCH APP
# ==========================================

demo.launch(share=True)